### ISSUE TITLE
Замена генерации иконки на более быстрый способ чем регулярным выражением

### ISSUE THREAD

**Issue by yunusga** [solversgroup/marmelad#18]
Меняем работу iconizer. После проведённых замеров компиляции шаблонов на тысячах иконок, выяснилось, что замена тэга иконки при помощи регулярного выражения, занимает достаточно долгое время. 

Основные требования к новой генерации иконок:
- управление тегом для иконки
- опции по настройке правил именования классов svg иконки (BEM)
- оборачивание блоком или присвоение класса для иконок с вращением (опционально)

Доп. идеи
- [x] SVG спрайт цветной/одноцветный

Необходимо решить/договориться как будет генерироваться иконка, макросом, шаблоном встроенным в заготовку или спец. функцией для шаблонизатора.

**Comment by ferz222** [comment]
Уберите пожалуйста вырезание цвета иконок. Иконки бывают цветные и удобнее их вставлять через iconizer. Вот например я хочу вставить logo сайта как SVG, зачем мне вставлять его напрямую, если я могу просто вставить его через iconizer?

Было бы совсем круто если в папке iconizer добавилась папка с SVG, у которых не происходит чистки стилей и цветов.

https://github.com/solversgroup/marmelad/blob/master/modules/gulp-iconizer/index.js#L89

**Comment by yunusga** [comment]
Интересное предложение. Логотип сайта можно просто заинлайнить в HTML. Хотя, если предположить что на странице будет использоваться цветная SVG-иконка более одного раза, то, имеет смысл сделать такой **цветной** SVG-спрайт. Раньше не сталкивались с такими кейсами. Работы по iconizer запланированы на следующую неделю, как раз посмотрим что и как устроено, изучим вопрос. Добавил в основное описание задачи цветной спрайт

**Comment by ferz222** [comment]
Например сейчас часто делают лого в шапке и подвале, и иногда они одинаковые. И в таком случае реально будет 2 одинаковых изображения + очень плохая читаемость кода, так как svg в большинстве случаев надо вставлять прямо в html из-за того, что они очень мало весят.
![2019-02-20 10 44 24](https://user-images.githubusercontent.com/9263386/53074733-8f2ced80-34fc-11e9-937a-783d94c1bea3.png)

Если SVG вставлять в `<img src="same.svg"/>`, то получаем серьёзные потери на запросы к серверу. Например мне сейчас надо вставить логотип в шапку весов 4кб, зачем мне его грузить с сервера, если он мне по любому нужен на каждой странице.

Надеюсь вы сделаете хорошее решение в следующем релизе:)
