### ISSUE TITLE
Лишние JS-библиотеки в заготовке проекта

### ISSUE THREAD

**Issue by yunusga** [solversgroup/marmelad#26]
Необходимо удалить все лишние JS-библиотеки из заготовки для проекта, оставить только `jquery.min.js` и `jquery.slim.min.js`

**Comment by yunusga** [comment]
@yunusga Интересно

**Comment by Litvinov-Victor** [comment]
Я это беру

**Comment by Litvinov-Victor** [comment]
https://github.com/solversgroup/marmelad/pulls
