### ISSUE TITLE
Cоздать модуль для уведомлений об ошибках на уровне ОС

### ISSUE THREAD

**Issue by yunusga** [solversgroup/marmelad#30]
т.к. в процессе разработки консоль обычно перекрыта редактором и браузером и не всегда понимаешь что в случае ошибки необходимо проверить консоль. Для избавления от этого косяка необходимо продумать куда и как выводить эти уведомления, в браузер, системный трей или звуковое уведомление.

Задача
Необходимо создать модуль для таких уведомлений на базе [node-notifier](https://www.npmjs.com/package/node-notifier)

**Comment by Litvinov-Victor** [comment]
https://pushjs.org/

**Comment by yunusga** [comment]
Не заработало в Хроме и для каждого проекта надо будет разрешать или не разрешать эти уведомления. Наверное нужны уведомления на уровне  ОС

**Comment by Litvinov-Victor** [comment]
Тогда можно попробовать https://www.npmjs.com/package/node-notifier

**Comment by Litvinov-Victor** [comment]
Я тогда возьмусь

**Comment by yunusga** [comment]
@ferz222 Выбрали ОС уведомления из опыта взаимодействия с софтом и распределения внимания между окнами редактора и браузера. Хотя 15ти секундное оповещение от BrowserSync тоже хорошо, но, увдеть ошибку сразу по её совершению думаю будет удобнее, т.к. бывает что в браузер не заглядываешь достаточно долго, пока что-то вояешь в проекте

**Comment by ferz222** [comment]
Я просто себе для работы купил монитор 21:9 и всегда перед глазами редактор и браузер. Сорян, не подумал про ситуацию переключения между окнами.

**Comment by yunusga** [comment]
@ferz222 C 21:9 не поспоришь

**Comment by Litvinov-Victor** [comment]
https://github.com/solversgroup/marmelad/tree/error-notification

**Comment by yunusga** [comment]
https://github.com/solversgroup/marmelad/tree/v7.10.11
